{{ config(materialized='table') }}

SELECT 
     DATE
    , PRODUCT_ID
    , PRODUCT_NAME
    , COUNT(DISTINCT CASE WHEN EVENT_TYPE = 'page_view' THEN EVENT_ID ELSE NULL END) AS VIEW_COUNT
    , COUNT(DISTINCT CASE WHEN EVENT_TYPE = 'added_to_cart' THEN EVENT_ID ELSE NULL END) AS ADDED_TO_CART_COUNT
    , COUNT(DISTINCT CASE WHEN EVENT_TYPE = 'checkout' THEN EVENT_ID ELSE NULL END) AS CHECKOUT_COUNT
FROM
    {{ ref('int_event_prod') }} 
GROUP BY 1,2,3